### ISSUE TITLE
NNLS?

### ISSUE THREAD

**Issue by brooksambrose** [ledell/subsemble#1]
Is non negative least squares available as a metalearner in subsemble?

**Comment by ledell** [comment]
Yes, I have a [pull request](https://github.com/ecpolley/SuperLearner/pull/21) open to add a `SL.nnls` wrapper to the SuperLearner package, but it has not been merged yet.  For now, you can copy-paste the `SL.nnls` wrapper from [here](https://github.com/ledell/h2oEnsemble-benchmarks/blob/master/src/utils/SuperLearner_wrappers.R).  This will be included in the next version of the SuperLearner package.

Once you have the `SL.nnls` and `predict.SL.nnls` functions sourced, you just specify the NNLS metalearner as a string, like usual:  `metalearner = "SL.nnls"`.
